# Information for the Readfile to gets its information
FolderToBackup = "FoldersTobackup"
LocationFolderToBackup = "./FoldersTobackup"
BackupFolder = "BackupFolder"
LocationBackupFolder = "./BackupFolder/"
MaxThreadsUsed = "1"
TimeSinceLastBackup = "20"
CompareFolderTime = "20"
FirstThreadSourceFile = LocationFolderToBackup + "/Backup1"
SecondThreadSourceFile = LocationFolderToBackup + "/Backup2"
ThirdThreadSourceFile = LocationFolderToBackup + "/Backup3"
FirstThreadTargetFile = LocationBackupFolder + "Backup1"
SecondThreadTargetFile = LocationBackupFolder + "/Backup2"
ThirdThreadTargetFile = LocationBackupFolder + "/Backup3"
TargetRecoveryfolder = "./RecoveryFolder"
RestoreZipFolder = "./RestoreZips"
